#!/bin/sh


# Gets Nginx tund opts.
nginx_tune_opts() {
	
#	PROCESSES=
#	PROCESSES_PROC_PERC=300
#	CONNECTIONS=
#	CONNECTIONS_MEM_PERC=1000
#	KEEPALIVE_REQUESTS=
#	KEEPALIVE_REQUESTS_MEM_PERC=200
#	MAX_KEEPALIVE_REQUESTS=10000
#	AIO_REQUESTS=16384
#	THREADS=
#	THREADS_PROC_PERC=3000
#	MAX_THREADS=256
#	THREAD_QUEUE=
#	THREAD_QUEUE_MEM_PERC=3000

	# OS limits.
	. os_limits
	available_cpus
	available_memory
	
	# CPU.
	if [ -z "${MAX_CPU}" ]
	then
		MAX_CPU="${AVAILABLE_CPUS}"
	fi
	
	# Max memory.
	if [ -z "${MAX_MEMORY}" ]
	then
		MAX_MEMORY="${AVAILABLE_MEMORY}"
	fi
	
	# Processes.
	if [ -z "${PROCESSES}" ] && [ ! -z "${PROCESSES_PROC_PERC}" ]
	then
		PROCESSES=$(( PROCESSES_PROC_PERC * MAX_CPU / 100 ))
	fi
	if [ -z "${PROCESSES}" ]
    then
        PROCESSES="auto"
    else 
		PROCESSES=$(( PROCESSES < 1 ? 1 : PROCESSES ))
    fi

	# Threads.
	if [ -z "${THREADS}" ]
	then
		THREADS=$(( THREADS_PROC_PERC * MAX_CPU / 100 ))
	fi
	THREADS=$((THREADS > MAX_THREADS ? MAX_THREADS : THREADS))
	THREADS=$((THREADS < 1 ? 1 : THREADS))
	if [ -z "${THREAD_QUEUE}" ]
	then
		THREAD_QUEUE=$(( THREAD_QUEUE_MEM_PERC * MAX_MEMORY / 100 ))
	fi
	
	# Connections.
	if [ -z "${CONNECTIONS}" ]
	then
		CONNECTIONS=$(( CONNECTIONS_MEM_PERC * MAX_MEMORY / 100 ))
	fi
	if [ -z "${KEEPALIVE_REQUESTS}" ]
	then
		KEEPALIVE_REQUESTS=$(( KEEPALIVE_REQUESTS_MEM_PERC * MAX_MEMORY / 100 ))
	fi
	KEEPALIVE_REQUESTS=$(( KEEPALIVE_REQUESTS > MAX_KEEPALIVE_REQUESTS ? MAX_KEEPALIVE_REQUESTS : KEEPALIVE_REQUESTS ))

	echo "MAX_MEMORY=${MAX_MEMORY}"
	echo "MAX_CPU=${MAX_CPU}"
	echo "PROCESSES=${PROCESSES}"
	echo "CONNECTIONS=${CONNECTIONS}"
	echo "KEEPALIVE_REQUESTS=${KEEPALIVE_REQUESTS}"
	echo "THREADS=${THREADS}"
	echo "THREAD_QUEUE=${THREAD_QUEUE}"
	export PROCESSES CONNECTIONS THREADS THREAD_QUEUE
}

#nginx_tune_opts
